language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.asc.enc -out local.secring.asc -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.asc.enc -out local.pubring.asc -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in credentials.sbt.enc -out local.credentials.sbt -d
script:
- sbt clean test compile
after_success:
- sbt ^publish-signed sonatypeRelease
env:
  global:
    secure: HzC46VdYc+6ADJaByDVFSsE8wYlbHOvaI3HjOscou2eJVHuAfz27Th9NwBD5yZ04/dKIzaxDdad5GSSH0pQ+ygHltrb4l5vGJ8/EtEGzzTwl1Hl7+akbJOWgqIqvJvQqoo36uMs90cZF3spCyokbgh+IFi3V3wJXhvaNinRLqZyYzLQ7jbUBEqpGPDzWH7hBbUzDOJeVya82Dz3zLVgT/AgGfEskKTHjkpjF4VpAG1R6tdcE8JSDt/wgK3v1drWCVyR0h2rdtvsYr3TmoyJjLuZ4Kw1xy44J/DTHUN4AT+ntyDibeImizbNxlxonJQji5PeXtiHmLIN7LO1ywZJaTMEFycr3XqfJf66GAMnECI2VbjQvbgLaug4nkFfgXuRCCS4v7tVHWx5XE7tnX1wVkTyTUz40bDwogSiNiwf8AwdZFcAGg/H4vTyNk9o/ShgB00ATV7uztslUDQNazl/CnamPZaYcmtKDDq/Uz86znlRl7CfLDOQYwJsAKDbQ6SXWehalEY3g0oWYf4PD+tmDmU3ko6omnIBWl0VlnTFtdJ1nv2H2LTqyDVX9qKkN+OyXNemPdD/+gsekkhnfQZX6caiHsPtZKuTNGfcfFvR/3FeJcO3LFdo6ZXXKnw9/GkGUiz8J8KkqfYP4SZFYHelTEkkzN+I0f9KCxGKgrVdBLnM=
